MODULE_NAME=mchw_odroid_xu
obj-m += $(MODULE_NAME).o
$(MODULE_NAME)-objs +=  mchw_core.o mc_experiments.o pmu_config_arm.o cbuffer.o monitoring_mod.o syswide.o \
			ipc_sampling_sf_mm.o smart_power_driver.o smart_power_mm.o smart_power_2_mm.o
EXTRA_CFLAGS := $(USER_CFLAGS) -DCONFIG_PMC_ARM -DODROID -DCONFIG_SMART_POWER -DCONFIG_SMART_POWER_2 -I$(src)/../include -I$(src)/..
