MODULE_NAME=mchw_odroid_xu
obj-m += $(MODULE_NAME).o 
PMCSCHED-objs= pmcsched.o dummy_plugin.o group_plugin.o	busybcs_plugin.o
$(MODULE_NAME)-objs +=  mchw_core.o mc_experiments.o pmu_config_arm.o cbuffer.o \
			monitoring_mod.o syswide.o ipc_sampling_sf_mm.o smart_power_driver.o \
			smart_power_mm.o smart_power_2_mm.o edp_core.o pmctrack_stub.o vexpress_sensors_core.o $(PMCSCHED-objs)

USER_CFLAGS ?=
#USER_CFLAGS ?= -ggdb -O0
EXTRA_CFLAGS += $(USER_CFLAGS) -DCONFIG_PMC_ARM -DODROID -DCONFIG_SMART_POWER -DCONFIG_SMART_POWER_2 -I$(src)/../include -I$(src)/..
