#!/usr/bin/env python
# -*- coding: utf-8 -*-

#
# pmctrack-gui
# Main application executable
#
##############################################################################
#
# Copyright (c) 2015 Jorge Casas <jorcasas@ucm.es>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
# MA 02110-1301, USA.
#
##############################################################################

import importlib
import wx
import gettext
from backend.user_config import *
from frames.pmc_frame_machine import *

version = "1.0.2"

translate = gettext.translation('pmctrackgui', localedir='locale', fallback=True)
translate.install()

app = wx.PySimpleApp(0)
wx.InitAllImageHandlers()

user_config = UserConfig()
init_frame = PMCFrameMachine(None, -1, "", version=version, user_config=user_config)
app.SetTopWindow(init_frame)
init_frame.Show()
app.MainLoop()
